### ISSUE TITLE
Some misspellings and wording suggestions in English

### ISSUE THREAD

**Issue by pkoby** [qiekub/map#26]
First off, thank you for creating this map! It's a great resource, although the tags are certainly underutilized in my area.

I noticed some misspellings on the main page, and looking in the code, I think they're relevant to the map/en.ftl file. I looked through the whole file and thought I would bring some points to your attention.

> `button_audience_queer_default_text = Queer Acceptence`
> `menu_text_audience_queer_everything = <strong>Dont't filter</strong> by queer acceptence.`

Should be spelled 'acceptance'. Also `Don't` has an extra t, here as well:
> `menu_text_published_everything = <strong>Dont't filter</strong> by published.`

> `subheader_follow_us = Follow us on...`
> `sources_placeholder = "Personal knowledge", links to websites...`

These have three periods (`...`) instead of an ellipsis (`…`) which most other values have. Not a big deal.

> `audience_heading_be_cautios = Please be cautios!`
> `audience_text_be_cautios = We don't yet know if this place is a safe space.`

Should be 'cautious'.

These last few are wording suggestions. I don't want to presume anything, but they sound a little awkward to me.
> `max_age_text = Till age {$age}.`

I would say "Up to age {$age}."

> `audience_input_label_primary = Primary for…`
> `menu_text_audience_queer_primary = <strong>Primary</strong> for queer people`
> `audience_primary_heading = Primary for:`

Although I know the OSM tag is `=primary`, in normal speech I would say "Primarily for".

I would try to make a pull request for this, but I have notoriously been unsuccessful with that in the past. Please let me know if this is fine.

**Comment by thomasrosen** [comment]
Thanks @ccamel for fixing this!
